# 
apiVersion: apps/v1  # Specifies the API version for the deployment resource in Kubernetes.
kind: Deployment     # Defines the type of resource. In this case, it's a Deployment, which manages a set of identical pods.
metadata:
  name: navya-speed # The name of the deployment. This is used to identify the deployment within the Kubernetes cluster.
  labels:               # Labels are key-value pairs used to organize and select resources.
    app: navya-speed # Label with key 'app' and value 'metaserver-app'. Useful for selecting the deployment's pods.
spec:
  replicas: 1           # Specifies that only one replica (pod) of the application should run.
  selector:
    matchLabels:
      app: navya-speed # The selector uses the label to find which pods are managed by this deployment.
  template:
    metadata:
      labels:
        app: navya-speed # Labels applied to the pods created by this deployment.
    spec:
      nodeSelector:
        #kubernetes.io/hostname: vehicle-node
        kubernetes.io/hostname: user-z790-aorus-elite
      containers:
      - name: navya-speed # The name of the container running within the pod.
        image: kaistmos/navya_speed:latest  # The Docker image to use for this container. It includes the application and all dependencies.
        env:                 # Defines environment variables that are passed to the container.
        - name: RABBITMQ_HOST
          #value: "143.248.55.76"
          value: "mos-rabbitmqcluster.default.svc.cluster.local"  # Hostname for connecting to the RabbitMQ service within the cluster.
        - name: RABBITMQ_PORT
          #value: "30672"
          value: "5672"  # The port on which RabbitMQ is listening.
        - name: RABBITMQ_USER
          value: "mos"  # Username for authenticating with RabbitMQ.
        - name: RABBITMQ_PASSWORD
          value: "mos"  # Password for authenticating with RabbitMQ.
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: MQTT_HOST
          value: "172.25.15.204"
        - name: SPEED_SUGGEST_QUEUE
          value: "speed-suggest-C1-V2"
        - name: TRAFFIC_STATE_QUEUE
          value: "M_traffic_total_Navya"
        ports:
        - containerPort: 1883  # The port on which the application inside the container will listen for incoming connections.
      restartPolicy: Always  # Specifies that the container should always be restarted if it fails.
