# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import custom_msg_pb2 as custom__msg__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in custom_msg_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VehicleStatusServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVehicleStatus = channel.unary_stream(
                '/VehicleStatusService/GetVehicleStatus',
                request_serializer=custom__msg__pb2.Empty.SerializeToString,
                response_deserializer=custom__msg__pb2.MosVehicleStatus.FromString,
                _registered_method=True)


class VehicleStatusServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetVehicleStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VehicleStatusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVehicleStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.GetVehicleStatus,
                    request_deserializer=custom__msg__pb2.Empty.FromString,
                    response_serializer=custom__msg__pb2.MosVehicleStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VehicleStatusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('VehicleStatusService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VehicleStatusService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetVehicleStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/VehicleStatusService/GetVehicleStatus',
            custom__msg__pb2.Empty.SerializeToString,
            custom__msg__pb2.MosVehicleStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SpeedSuggestionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetSpeedSuggest = channel.unary_unary(
                '/SpeedSuggestionService/SetSpeedSuggest',
                request_serializer=custom__msg__pb2.MosSpeedSuggest.SerializeToString,
                response_deserializer=custom__msg__pb2.Empty.FromString,
                _registered_method=True)


class SpeedSuggestionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetSpeedSuggest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeedSuggestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetSpeedSuggest': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSpeedSuggest,
                    request_deserializer=custom__msg__pb2.MosSpeedSuggest.FromString,
                    response_serializer=custom__msg__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SpeedSuggestionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SpeedSuggestionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpeedSuggestionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetSpeedSuggest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SpeedSuggestionService/SetSpeedSuggest',
            custom__msg__pb2.MosSpeedSuggest.SerializeToString,
            custom__msg__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TrafficStateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetTrafficState = channel.unary_unary(
                '/TrafficStateService/SetTrafficState',
                request_serializer=custom__msg__pb2.MosTrafficState.SerializeToString,
                response_deserializer=custom__msg__pb2.Empty.FromString,
                _registered_method=True)


class TrafficStateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetTrafficState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrafficStateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetTrafficState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTrafficState,
                    request_deserializer=custom__msg__pb2.MosTrafficState.FromString,
                    response_serializer=custom__msg__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TrafficStateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('TrafficStateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrafficStateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetTrafficState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TrafficStateService/SetTrafficState',
            custom__msg__pb2.MosTrafficState.SerializeToString,
            custom__msg__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
